export type {
  ChangeTaskStatusRequest,
  CreateLearningProjectRequest,
  CreateLearningTaskRequest,
  CreateTaskCommentRequest,
  LearningProject,
  LearningTask,
  ListTaskParams,
  PageResult,
  TaskActivity,
  TaskComment,
  TaskStatistics,
  TaskStatus,
  TaskTag,
  UpdateLearningTaskRequest,
} from '@learn-java/task-domain'
